INSERT INTO clothes (clothes_name, temperature_level) values ('민소매', 1);
INSERT INTO clothes (clothes_name, temperature_level) values ('반팔', 1);
INSERT INTO clothes (clothes_name, temperature_level) values ('반바지', 1);
INSERT INTO clothes (clothes_name, temperature_level) values ('여름 원피스', 1);
INSERT INTO clothes (clothes_name, temperature_level) values ('반팔', 2);
INSERT INTO clothes (clothes_name, temperature_level) values ('얇은 셔츠', 2);
INSERT INTO clothes (clothes_name, temperature_level) values ('반바지', 2);
INSERT INTO clothes (clothes_name, temperature_level) values ('면바지', 2);
INSERT INTO clothes (clothes_name, temperature_level) values ('얇은 가디건', 3);
INSERT INTO clothes (clothes_name, temperature_level) values ('긴팔', 3);
INSERT INTO clothes (clothes_name, temperature_level) values ('면바지', 3);
INSERT INTO clothes (clothes_name, temperature_level) values ('청바지', 3);
INSERT INTO clothes (clothes_name, temperature_level) values ('얇은 니트', 4);
INSERT INTO clothes (clothes_name, temperature_level) values ('맨투맨', 4);
INSERT INTO clothes (clothes_name, temperature_level) values ('가디건', 4);
INSERT INTO clothes (clothes_name, temperature_level) values ('청바지', 4);
INSERT INTO clothes (clothes_name, temperature_level) values ('자켓', 5);
INSERT INTO clothes (clothes_name, temperature_level) values ('가디건', 5);
INSERT INTO clothes (clothes_name, temperature_level) values ('야상', 5);
INSERT INTO clothes (clothes_name, temperature_level) values ('청바지', 5);
INSERT INTO clothes (clothes_name, temperature_level) values ('면바지', 5);
INSERT INTO clothes (clothes_name, temperature_level) values ('자켓', 6);
INSERT INTO clothes (clothes_name, temperature_level) values ('트렌치코트', 6);
INSERT INTO clothes (clothes_name, temperature_level) values ('야상', 6);
INSERT INTO clothes (clothes_name, temperature_level) values ('니트', 6);
INSERT INTO clothes (clothes_name, temperature_level) values ('청바지', 6);
INSERT INTO clothes (clothes_name, temperature_level) values ('코트', 7);
INSERT INTO clothes (clothes_name, temperature_level) values ('가죽자켓', 7);
INSERT INTO clothes (clothes_name, temperature_level) values ('히트텍', 7);
INSERT INTO clothes (clothes_name, temperature_level) values ('니트', 7);
INSERT INTO clothes (clothes_name, temperature_level) values ('패딩', 8);
INSERT INTO clothes (clothes_name, temperature_level) values ('두꺼운 코트', 8);
INSERT INTO clothes (clothes_name, temperature_level) values ('목도리', 8);
INSERT INTO clothes (clothes_name, temperature_level) values ('기모제품', 8);

